In [1]:
import lynse

In [2]:
client = lynse.VectorDBClient()
my_db = client.create_database("my_vec_db", drop_if_exists=True)

In [3]:
collection = my_db.require_collection(collection='test_vec', dim=128, drop_if_exists=True, warm_up=True)

In [4]:
from tqdm import trange

import numpy as np

with collection.insert_session() as session:
    vectors = []
    for i in range(1000000):
        if i == 0:
            query = np.random.random(128)
            vec = query
        else:
            vec = np.random.random(128)

        vectors.append((vec, i, {"test":f"test_{i // 1000}"}))
    session.bulk_add_items(vectors)


2024-09-30 13:31:17 - LynseDB - INFO - Saving data...
2024-09-30 13:31:17 - LynseDB - INFO - Writing chunk to storage...
Data persisting: 100%|██████████| 10/10 [00:03<00:00,  2.56chunk/s]

2024-09-30 13:31:21 - LynseDB - INFO - Writing chunk to storage done.
2024-09-30 13:31:21 - LynseDB - INFO - Pre-building the index...
2024-09-30 13:31:21 - LynseDB - INFO - Building an index using the `Flat-IP` index mode...


## Run a query

In [5]:
collection.search(np.random.random(128), k=12)

(array([884279, 552621, 153056, 691264, 134195, 336895, 918358, 325766,
        745979, 258086, 450323, 540659]),
 array([42.094948, 42.091545, 42.058136, 41.590088, 41.540943, 41.50928 ,
        41.495872, 41.35817 , 41.241226, 41.21544 , 41.19685 , 41.13687 ],
       dtype=float32),
 None)

## Using the threads to speed up queries

In [7]:
collection = my_db.require_collection('test_vec', warm_up=True, n_threads=12)


2024-09-30 13:31:33 - LynseDB - INFO - Collection 'test_vec' already exists. Loaded.
2024-09-30 13:31:34 - LynseDB - INFO - Pre-building the index...
2024-09-30 13:31:34 - LynseDB - INFO - Building an index using the `Flat-IP` index mode...


In [8]:
import numpy as np

collection.search(np.random.random(128), k=12)

(array([918358, 886888, 227134, 499889, 349036, 272292, 681918, 450323,
         80205, 310839, 843673,  78264]),
 array([36.165974, 35.993546, 35.903637, 35.770725, 35.627327, 35.56774 ,
        35.52246 , 35.39807 , 35.345047, 35.33812 , 35.270313, 35.2631  ],
       dtype=float32),
 None)

## Using Filter to narrow down the search range

In [9]:
import operator

from lynse.field_models import Filter, FieldCondition, MatchField, MatchID


collection.search(
    vector=np.random.random(128), 
    k=10, 
    search_filter=Filter(
        must=[
            FieldCondition(key='test', matcher=MatchField('test_0')),  # Support for filtering fields
            FieldCondition(key=":match_id:", matcher=MatchID([1, 2, 3, 4, 5]))  # Support for filtering IDs
        ], 
        any=[
            FieldCondition(key='field', matcher=MatchField('test_1')),
            FieldCondition(key='order', matcher=MatchField(8, comparator=operator.ge)),
            FieldCondition(key=":match_id:", matcher=MatchID([1, 2, 3, 4, 5])),
        ]
    )
)

(array([3, 2, 1, 4, 5]),
 array([36.31994 , 32.760193, 32.382797, 30.648108, 27.064667],
       dtype=float32),
 None)